name: Deploy to Azure Container Instances

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Authenticate with Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy container using explicit CLI command (matches your manual version)
      - name: Create/Update Container Instance
        run: |
          az container delete \
            --resource-group RGR-ACR \
            --name getting-started \
            --yes || true  # Ignore error if container doesn't exist

          az container create \
            --resource-group RGR-ACR \
            --name getting-started \
            --image registryvanmehdi.azurecr.io/gettingstarted:v1 \
            --azure-file-volume-share-name sharevanmehdi \
            --azure-file-volume-account-name storagevanmehdi \
            --azure-file-volume-account-key "${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}" \
            --azure-file-volume-mount-path /etc/todos \
            --ports 3000 \
            --os-type Linux \
            --restart-policy Always
